// This file is auto-generated by generate_models.sh. Do not edit manually.
export const characterModels = {};
characterModels['Concindia'] = { parts: [], welds: [] };
characterModels['Concindia'].parts.push({name:'Body', shape:'Sphere', material:'MossyFabric', color:'#228B22', size:[
  1,
  1,
  1
], position:[
  0,
  1,
  0
]});
characterModels['Concindia'].parts.push({name:'WingLeft', shape:'Plane', material:'Leaf', color:'#00ff00', size:[
  0.5,
  1,
  0.01
], position:[
  -0.4,
  1,
  0
]});
characterModels['Concindia'].parts.push({name:'WingRight', shape:'Plane', material:'Leaf', color:'#00ff00', size:[
  0.5,
  1,
  0.01
], position:[
  0.4,
  1,
  0
]});
characterModels['Concindia'].welds.push({part0:'Body', part1:'WingLeft'});
characterModels['Concindia'].welds.push({part0:'Body', part1:'WingRight'});
characterModels['Elda'] = { parts: [], welds: [] };
characterModels['Elda'].parts.push({name:'Body', shape:'Sphere', material:'MagicalFabric', color:'#ffffaa', size:[
  0.5,
  0.5,
  0.5
], position:[
  0,
  1,
  0
]});
characterModels['Elda'].parts.push({name:'WingLeft', shape:'Plane', material:'EnergyWings', color:'#ffffff', size:[
  0.2,
  0.5,
  0.01
], position:[
  -0.2,
  1,
  0
]});
characterModels['Elda'].parts.push({name:'WingRight', shape:'Plane', material:'EnergyWings', color:'#ffffff', size:[
  0.2,
  0.5,
  0.01
], position:[
  0.2,
  1,
  0
]});
characterModels['Elda'].welds.push({part0:'Body', part1:'WingLeft'});
characterModels['Elda'].welds.push({part0:'Body', part1:'WingRight'});
characterModels['Ghosts'] = { parts: [], welds: [] };
characterModels['Ghosts'].parts.push({name:'Body', shape:'Cylinder', material:'Ethereal', color:'#ccccff', size:[
  0.5,
  1.5,
  0.5
], position:[
  0,
  1,
  0
]});
characterModels['Lava Spiders'] = { parts: [], welds: [] };
characterModels['Lava Spiders'].parts.push({name:'Body', shape:'Sphere', material:'VolcanicStone', color:'#ff4500', size:[
  0.5,
  0.5,
  0.5
], position:[
  0,
  0.5,
  0
]});
characterModels['Lava Spiders'].parts.push({name:'Leg0', shape:'Cylinder', material:'Obsidian', color:'#8B0000', size:[
  0.05,
  0.5,
  0.05
], position:[
  0.3,
  0.5,
  0
]});
characterModels['Lava Spiders'].parts.push({name:'Leg1', shape:'Cylinder', material:'Obsidian', color:'#8B0000', size:[
  0.05,
  0.5,
  0.05
], position:[
  -0.3,
  0.5,
  0
]});
characterModels['Lava Spiders'].welds.push({part0:'Body', part1:'Leg0'});
characterModels['Lava Spiders'].welds.push({part0:'Body', part1:'Leg1'});
characterModels['The Beast'] = { parts: [], welds: [] };
characterModels['The Beast'].parts.push({name:'Body', shape:'Block', material:'Obsidian', color:'#1a1a1a', size:[
  10,
  20,
  10
], position:[
  0,
  10,
  0
]});
characterModels['The Beast'].parts.push({name:'HeadBase', shape:'Block', material:'Obsidian', color:'#1a1a1a', size:[
  3,
  3,
  3
], position:[
  0,
  21,
  0
]});
characterModels['The Beast'].parts.push({name:'Head0', shape:'Sphere', material:'Obsidian', color:'#660000', size:[
  2,
  2,
  2
], position:[
  -2,
  22,
  0
]});
characterModels['The Beast'].parts.push({name:'Head1', shape:'Sphere', material:'Obsidian', color:'#660000', size:[
  2,
  2,
  2
], position:[
  2,
  22,
  0
]});
characterModels['The Beast'].parts.push({name:'LowerHornLeft', shape:'Cylinder', material:'Obsidian', color:'#1a1a1a', size:[
  0.5,
  3,
  0.5
], position:[
  -1,
  22,
  0
]});
characterModels['The Beast'].parts.push({name:'LowerHornRight', shape:'Cylinder', material:'Obsidian', color:'#1a1a1a', size:[
  0.5,
  3,
  0.5
], position:[
  1,
  22,
  0
]});
characterModels['The Beast'].welds.push({part0:'Body', part1:'HeadBase'});
characterModels['The Beast'].welds.push({part0:'HeadBase', part1:'Head0'});
characterModels['The Beast'].welds.push({part0:'HeadBase', part1:'Head1'});
characterModels['The Beast'].welds.push({part0:'HeadBase', part1:'LowerHornLeft'});
characterModels['The Beast'].welds.push({part0:'HeadBase', part1:'LowerHornRight'});
characterModels['Walking Pumpkins'] = { parts: [], welds: [] };
characterModels['Walking Pumpkins'].parts.push({name:'Body', shape:'Sphere', material:'Organic', color:'#ffa500', size:[
  0.6,
  0.6,
  0.6
], position:[
  0,
  0.5,
  0
]});
characterModels['Walking Pumpkins'].parts.push({name:'VineLegFront', shape:'Cylinder', material:'Vine', color:'#006400', size:[
  0.05,
  0.4,
  0.05
], position:[
  0,
  0.3,
  0.2
]});
characterModels['Walking Pumpkins'].parts.push({name:'VineLegBack', shape:'Cylinder', material:'Vine', color:'#006400', size:[
  0.05,
  0.4,
  0.05
], position:[
  0,
  0.3,
  -0.2
]});
characterModels['Walking Pumpkins'].welds.push({part0:'Body', part1:'VineLegFront'});
characterModels['Walking Pumpkins'].welds.push({part0:'Body', part1:'VineLegBack'});
